export const PADROES_BACKGROUND = {
  raysOrigin: "top-center",
  raysColor: "#ffffff",
  raysSpeed: 1,
  lightSpread: 1,
  rayLength: 2,
  pulsating: false,
  fadeDistance: 1.0,
  saturation: 1.0,
  followMouse: true,
  mouseInfluence: 0.1,
  noiseAmount: 0.0,
  distortion: 0.0,
  intensity: 1.0,
  dprMax: 2,
};